name: Create GitHub release tag

on:
  push:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install poetry and poetry-dynamic-versioning
      run: |
        curl -sSL https://install.python-poetry.org | python3 -
        export PATH=$HOME/.local/bin:$PATH
        poetry self add "poetry-dynamic-versioning[plugin]"
    - name: Create draft release
      run: |
        SEMANTIC_VERSION=$(poetry version | cut -d ' ' -f 2)
        TAG="prefix-v$SEMANTIC_VERSION"
        DRAFT_RELEASE_ID=$(gh api -H "Accept: application/vnd.github+json" /repos/takaiyuk/poetry-dynamic-versioning-example/releases | jq -rjc '.[] | select(.draft==true) | .id')
        if [ -z "${DRAFT_RELEASE_ID}" ]; then
          echo "Creating a new draft release..."
          gh release create $TAG --draft --generate-notes
        else
          echo "Updating the existing draft release..."
          LATEST_TAG=$(git describe --abbrev=0 --tags)
          BODY="**Full Changelog**: https://github.com/$GITHUB_REPOSITORY/compare/$LATEST_TAG...$TAG"
          gh api \
            --method PATCH \
            -H "Accept: application/vnd.github+json" \
            /repos/$GITHUB_REPOSITORY/releases/$DRAFT_RELEASE_ID \
            -f tag_name=$TAG \
            -f target_commitish='main' \
            -f name=$TAG \
            -f body="$BODY" \
            -F draft=true
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
